### ISSUE TITLE
Some converted files returned static only.

### ISSUE THREAD

**Issue by nascimentohugo** [fukidzon/Rode_WirelessGoII_UGG2wav#1]
Hello. 
Done some more recordings. Some files only obtained continuous static. 
At first i thought it was something i've done, but after i've exported from Rode Central, audio seems good. 
Converted ones not. 
Thanks.
File: [https://hugonascimento.com/_upload/GITHUB/samples-test-convert-Go-II.zip](url)

**Comment by fukidzon** [comment]
This tool only exports the uncompressed 24bit 48kHz raw PCM data from the UGG files ... your transmitters were set to "compressed" recording (it's also visible when looking at the size of the files - when uncompressed, the UGG file has approx the same size as the WAV file) ...look at https://www.rode.com/blog/all/Wireless-GO-II-On-Board-Recording-and-Audio-Export-Modes-Explained for the compressed/uncompressed setting of the recording in the transmitters

**Comment by nascimentohugo** [comment]
Forgot i've changed that setting after and didn't remember your description. Thanks!
Awesome tool! Will it be able, or even be possible to make this work also for uncompressed?
H.

**Comment by fukidzon** [comment]
Unfortunately I don't think I can do it for the compressed files - I could find the same data in the converted WAV and the uncompressed UGG file and find out what it's needed to copy from the UGG files, but I don't have any clue what kind of compression they use
