### ISSUE TITLE
Using this on MacOS

### ISSUE THREAD

**Issue by Mei-Lewis-Mei** [fukidzon/Rode_WirelessGoII_UGG2wav#2]
Hi

Very useful tool thanks loads for making this!

I had quite a lot of trouble getting it to work at first for me on MacOS.
I finally figured out that I need to use Python 3 for it to work, which on MacOS looks like:

> python3 ugg2wav.py REC00032.UGG

This may be me being stupid, I know very little about Python, but I thought it might be worth mentioning in case others have the same issue

**Comment by fukidzon** [comment]
I'm happy you find it useful! :)

Thanks for pointing this out - yes, sometimes it's `python3`
