### ISSUE TITLE
wrapper bash script for converting multiple files... 

### ISSUE THREAD

**Issue by tmuka** [fukidzon/Rode_WirelessGoII_UGG2wav#3]
Thanks for the useful tool!

I made a quick bash wrapper script for your python script so I can easily run it in a directory to convert multiple files that have not already been converted.

The contents of the ugg2wawv.sh script are...
```bash
#!/bin/bash
ls -1 *REC*.UGG *REC*.wav | sed 's;.wav;;gi' | uniq -u | xargs -L1 python3 ~/bin/ugg2wav.py
```

I realize a weakness of the default Rode file naming scheme is that blindly copying recording files from multiple transmitter devices into the same directory may cause collisions. So it's probably best to copy each device's recordings to different directories.  

A simple idea for enhancing your script might be to generate an md5 hash of the original file to append into the output wav filename.   Any that's probably still overkill for anyone that made it this far :D

**Comment by tmuka** [comment]
another useful enhancement idea would be to try to preserve the original file metadata datetime with the newly created .wav file.

**Comment by tmuka** [comment]
I modified the script a bit more to preserve the original .UGG file datetime.   feel free to incorporate this if you like.  

```python
# Converting UGG files from Rode Wireless Go II transmitters (unsompressed recordings) to WAV format
# Author: Jan Mazanec, https://github.com/fukidzon, jmazanec@gmail.com
# 3.11.2021
# needed libraries: wave (install as `pip install wave`)

# usage: `python ugg2wav.py REC00032.UGG`
# created WAV file is then REC00032.UGG.wav

import sys
import wave

# add imports to preserve original mtime
import os
import time
import datetime
import glob

# get filename and read the lines
if not len(sys.argv) > 1:
    sys.exit("provide a filename")
filename = sys.argv[1]
try:
    with open(filename, 'rb') as f:
        original_datetime = os.stat(filename).st_mtime
        s = f.read()
except IOError as e:
    sys.exit("Couldn't open file {}.".format(e))

def get_data_from_frame(frame):
    if frame[5]!=0:
        return []
    else:
        return frame[44:] # at byte 44 the data starts, hard to say what is the first 44bytes, because it doesn't really conform the Ogg stadard

#print("length: ", len(s))

data = b''
data_list = []

frame_start = s.find(b'OggS',0) # The UGG format is similar to Ogg format, but not compatible. But in The UGG files, OggS marks new page of data
while frame_start != -1:

    frame_end = s.find(b'OggS', frame_start + 4)
    frame_type = s[frame_start+5] # 2 is starting frame, 0 is frame with data, 4 is end frame
    if frame_type == 0:
        #data += get_data_from_frame(s[frame_start:frame_end]) # appending is slow, joining array is much faster
        data_list.append(get_data_from_frame(s[frame_start:frame_end]))
    #print(frame_start, frame_end, frame_end-frame_start, frame_type)
    # print progress
    #print("{:.1f}%".format(100*frame_start/len(s)))
    frame_start = frame_end

data = b''.join(data_list)

with wave.open(filename + ".wav", "w") as f:
    f.setnchannels(1)
    f.setsampwidth(3)
    f.setframerate(48000)
    f.writeframes(data)

# update new wav file datetime to match original file mtime
os.utime(filename + ".wav", (original_datetime,original_datetime))
```

**Comment by MKBontwikkeling** [comment]
Thanks for the addition. How can you access the storage? My systems (both Win and Mac) lockup when I try to access them.

**Comment by tmuka** [comment]
sure thing. I'm manually copy and pasting the files using window explorer
from the transmitter onto a different directory on my hard drive. then, I'm
actually running the script in Windows 10 subsystem for Linux (wsl).

i haven't tried mounting the device with the script.

i do wish Rode would change the read only access to that drive. so in the
very least I could rename it to identify which of my two transmitters is
plugged in!

**Comment by MKBontwikkeling** [comment]
I'm using Powershell on Win10. Works like a charm. Totally agree on the read-only part. I was able to rename the units in the Central app by clicking on the names. I'm not sure if that also renames the device in explorer because I can't test it out. Maybe that helps.

**Comment by fukidzon** [comment]
@tmuka thanks for the time preserving suggestion! - I added it to the script

**Comment by kahlos** [comment]
Really helpful script, thanks @fukidzon! Just expanding upon @tmuka's efforts, I've made a shell script to convert all .UGG files in all subfolders in the input directory to an output directory with .wav extensions

```
# 2021-12-05
# Uses ugg2wav.py to convert all files in input directory including subdirectories
# Usage: sh ugg_convert.sh directorytoconvert

OUTPUT_DIR=ugg_convert_output

echo Creating output directories
for i in $1/*/
do
  mkdir -pv $OUTPUT_DIR/$i 
done

echo Converting all files in $1
for i in $1/*/*.UGG
do
  echo Converting $i
  python ugg2wav.py $i
  mv -v $i.wav $OUTPUT_DIR/${i%%.*}.wav
done
```

**Comment by tysnaden** [comment]
> Really helpful script, thanks @fukidzon! Just expanding upon @tmuka's efforts, I've made a shell script to convert all .UGG files in all subfolders in the input directory to an output directory with .wav extensions
> 
> ```
> # 2021-12-05
> # Uses ugg2wav.py to convert all files in input directory including subdirectories
> # Usage: sh ugg_convert.sh directorytoconvert
> 
> OUTPUT_DIR=ugg_convert_output
> 
> echo Creating output directories
> for i in $1/*/
> do
>   mkdir -pv $OUTPUT_DIR/$i 
> done
> 
> echo Converting all files in $1
> for i in $1/*/*.UGG
> do
>   echo Converting $i
>   python ugg2wav.py $i
>   mv -v $i.wav $OUTPUT_DIR/${i%%.*}.wav
> done
> ```

Where would this be placed in the original code?

**Comment by ghost** [comment]
Hey can someone please tell me how to use this script? I've never used Python before and desperately need help. Or just quickly point me to some resources to help me get started if its too difficult to explain.

**Comment by kahlos** [comment]
> > Really helpful script, thanks @fukidzon! Just expanding upon @tmuka's efforts, I've made a shell script to convert all .UGG files in all subfolders in the input directory to an output directory with .wav extensions
> > 
> > ```
> > # 2021-12-05
> > # Uses ugg2wav.py to convert all files in input directory including subdirectories
> > # Usage: sh ugg_convert.sh directorytoconvert
> > 
> > OUTPUT_DIR=ugg_convert_output
> > 
> > echo Creating output directories
> > for i in $1/*/
> > do
> >   mkdir -pv $OUTPUT_DIR/$i 
> > done
> > 
> > echo Converting all files in $1
> > for i in $1/*/*.UGG
> > do
> >   echo Converting $i
> >   python ugg2wav.py $i
> >   mv -v $i.wav $OUTPUT_DIR/${i%%.*}.wav
> > done
> > ```
> 
> Where would this be placed in the original code?

This is a bash script, so I don't think it can be used within the original python. You can copy it and save as a .sh file, which can be run in terminal on Linux or MacOS. On windows I think powershell will run it.

**Comment by kahlos** [comment]
> Hey can someone please tell me how to use this script? I've never used Python before and desperately need help. Or just quickly point me to some resources to help me get started if its too difficult to explain.

I presume you're using windows? First download python and try to get the original authors code running (you might need to pip install some python packages). Then use window powershell to use the above script on a bunch of files.

Hope that helps!

**Comment by monkvagabond** [comment]
Hey folks,
Musician here. I would love to use this code because I too have a lot .UGG files lying around, but I can't even figure how to start with all this. Could someone maybe write a small step by step guide for us dummies? Or even create a little app on donation basis. I would gladly tip!

Thanks for your contributions!

**Comment by fukidzon** [comment]
I just updated the script so it accepts also a directory as argument and in that case it converts all .UGG files in that directory. 

Also a link in Readme to installation of Python in Windows was added - I hope it can help those who are not familiar with Python so they understand how running python scripts in command prompt works

**Comment by gatalex** [comment]
I change the UGG extension for Wav and it works, you don't need any code.
