### ISSUE TITLE
Just awesome hahaha

### ISSUE THREAD

**Issue by MKBontwikkeling** [fukidzon/Rode_WirelessGoII_UGG2wav#4]
I'm a real noob when it comes to Github but just wanted to thank you for the fix! It's awesome!

By the way; right now I can only access the storage on my Android device. If I use Win or Mac to access the storage it doesn't work. Is there a way to bypass the accessing issues on Windows?

Thanks again for the effort!

**Comment by tmuka** [comment]
have you installed the Rode Central app in Windows? when I launch that with
a transmitter connected a Windows explorer window opens with all the .OGG
files read only. then I can copy and paste those to my hard drive and run
the script.

**Comment by MKBontwikkeling** [comment]
Hi Tony. Yes I have, but it doesn't work. I can't access the files in either Rode Central or directly through the Explorer. I couldn't accesss them on my Mac as well. I can access the files by connecting the unit to my Android devices, so the units probably aren't faulty, just the software.

**Comment by jasalt** [comment]
Do you connect the receiver or the TX unit (with microphone) to PC/Mac? Make sure you connect just the TX unit via USB-C, open Rode Central and it mounts read-only on Mac, after updating the unit firmware.

If not, sounds more like something that Rode support can help with, or returning unit for warranty repair.

**Comment by MKBontwikkeling** [comment]
@jasalt Yes, I connect the TX to the pc. I can access the 'read only'-volume now. Recent update forces me to have the Central-app open before I can see the volume. Since I can access the volume and use the files with this script, it's hard not to point to Rode's licensing fiddling bull as the culprit. They just need to fix this.

Ps. It's my second set of devices and I've had several conversations with Rode's customer service. They say they're working on it.
