### ISSUE TITLE
NOOB Q - pip install wave

### ISSUE THREAD

**Issue by tysnaden** [fukidzon/Rode_WirelessGoII_UGG2wav#5]
Hi, first all, thanks for developing this. I can't wait to try it out. Currently shooting a doc and love the WGII's but the workflow is brutal. I record everything to the packs uncompressed, so I'm assuming with will work - especially with the rename wrapper.

I'm a photographer and filmmaker - don't know s##t about coding, and I'm having issues running the pip install wave command.

I installed python3 (Mac) and have tried it like this (without the hyphens):

-python3>
pip install wave-

and

 python3 pip install wave

Also with W on wave upper case.

If you could steer me in the right direction of what I'm doing wrong, I'd greatly appreciate it.

Aslo ---

What's with the .egg files? Are these similar to the .pkf's that Adobe Audition exports alongside a wave, or a .xml file?

Thanks again!

**Comment by tmuka** [comment]
@tysnaden It looks like maybe you're trying to run `pip` inside of python, but it should be run from your default command prompt, not inside of python. 

I suspect the .egg files contain the rode marker/flag information that you can see inside the rode central app. 

hope this helps!

**Comment by tysnaden** [comment]
Thank you!

for anyone else with the same issue, this worked for me:

python3 -m pip install --upgrade pip >
python3 -m pip install Wave
