### ISSUE TITLE
Files not usable ?

### ISSUE THREAD

**Issue by Camille92** [fukidzon/Rode_WirelessGoII_UGG2wav#8]
Hello there,

I'm running your script, but the result I get if full of white noise and not usable.

Any idea what happened ?

Thanks for your help

**Comment by fukidzon** [comment]
the on-board recording has to be set to "uncompressed recording": https://rode.com/en/about/news-info/Wireless-GO-II-On-Board-Recording-and-Audio-Export-Modes-Explained ... I hope the haven't changed the format of the recording in a new update :)
